// ARIA Diff Alerts — Auto-generated by diff_alerts.py
// Comparing: 2026-04-15 → 2026-04-16
// DO NOT EDIT MANUALLY

const ARIA_DIFF = {
  summary: {
  "prev_date": "2026-04-15",
  "curr_date": "2026-04-16",
  "prev_total": 3755,
  "curr_total": 3755,
  "net_change": 0,
  "new_domains": 0,
  "removed_domains": 0,
  "newly_active": 0,
  "newly_inactive": 0,
  "new_critical": 0,
  "sev_escalated": 0,
  "generated_at": "2026-04-16T10:44:14.353473Z"
},
  alerts:  []
};
