// ARIA Diff Alerts — Auto-generated by diff_alerts.py
// Comparing: 2026-05-17 → 2026-05-18
// DO NOT EDIT MANUALLY

const ARIA_DIFF = {
  summary: {
  "prev_date": "2026-05-17",
  "curr_date": "2026-05-18",
  "prev_total": 3755,
  "curr_total": 3755,
  "net_change": 0,
  "new_domains": 0,
  "removed_domains": 0,
  "newly_active": 0,
  "newly_inactive": 0,
  "new_critical": 0,
  "sev_escalated": 0,
  "generated_at": "2026-05-18T10:20:43.227518Z"
},
  alerts:  []
};
